channels:
- conda-forge
dependencies:
- hatchling =1.31.0
- hatch-vcs =0.5.0
- hatch-jupyter-builder >=0.9.1
- aimsgb =1.1.1
- anywidget =0.11.0
- ase =3.29.0
- assyst =0.16.0
- atomistics =0.3.8
- bader =1.0.5
- black =26.5.1
- calphy =2.0.1
- conda =26.7.0
- conda-smithy =2026.8.5
- coverage =7.15.3
- custodian =2025.12.14
- duckdb =1.5.5
- dynaphopy =1.19.0
- executorlib =1.10.1
- ffmpeg =8.1.2
- flux-core =0.87.0
- flux-sched =0.53.0
- git =2.55.0
- git-filter-repo =2.47.0
- gpaw =25.7.0
- grace-tensorpotential =0.6.0
- graphviz =14.1.2
- grayskull =3.1.1
- gunicorn =26.0.0
- h5io =0.2.5
- h5io_browser =0.2.16
- iprpy-data =2025.01.14
- ipytree =0.2.2
- jupyter_app_launcher =0.3.2
- jupyterlab =4.6.2
- jupyter-server-proxy =4.5.0
- jupyterhub =5.5.0
- lammps =2024.08.29=*openmpi*
- landau =1.11.0
- langchain =1.3.14
- langchain-anthropic =1.5.4
- langchain-openai =1.4.1
- lxml =6.1.1
- mamba =2.8.1
- matplotlib-base =3.11.1
- marimo =0.23.16
- mkl =2026.1.0
- mpi4py =4.1.2
- mypy =2.3.0
- nglview =4.0.1
- netcdf4 =1.7.4
- numba =0.66.0
- openkim-models =2021.01.28
- pre-commit =4.6.1
- psycopg2 =2.9.12
- pyauthenticator =0.4.0
- pygraphviz =1.14
- pyiron =0.5.2
- pyiron-data =0.0.31
- pyiron_atomistics =0.8.11
- pyiron_potentialfit =0.3.15
- pyiron_snippets =1.4.0
- pyiron_workflow =0.19.1
- pylammpsmpi =0.5.0
- pymace =0.3.16
- pymov2gif =0.0.3
- pysqa =0.4.4
- python =3.12.13
- python-ace =0.3.1
- python-ternary =1.0.8
- pytorch =2.12.0
- pyxtal =1.1.4
- qe =7.5
- rdkit =2026.03.5
- seaborn =0.13.2
- sim-atlas-toolkit =0.0.10
- sphinxdft =3.1
- semantikon =1.4.0
- sqsgenerator =0.5.6
- sysroot_linux-64 =2.39
- tensorflow =2.19.1
- wget =1.25.0
- pip
- pip:
  - marimo-jupyter-extension=0.23.16
name: base
