channels: 
- conda-forge
dependencies: 
- hatchling
- hatch-vcs
- hatch-jupyter-builder
- aimsgb
- anywidget
- ase
- assyst
- atomistics
- bader
- black
- calphy
- conda
- conda-smithy
- coverage
- custodian
- duckdb
- dynaphopy
- executorlib
- ffmpeg
- flux-core
- flux-sched
- git
- git-filter-repo
- gpaw
- grace-tensorpotential
- graphviz
- grayskull
- gunicorn
- h5io
- h5io_browser
- iprpy-data
- ipytree
- jupyter_app_launcher
- jupyterlab
- jupyter-server-proxy
- jupyterhub
- lammps
- landau
- langchain
- langchain-anthropic
- langchain-openai
- lxml
- mamba
- matplotlib-base
- marimo
- mkl
- mpi4py
- mypy
- nglview
- netcdf4
- numba
- openkim-models
- pre-commit
- psycopg2
- pyauthenticator
- pygraphviz
- pyiron
- pyiron-data
- pyiron_atomistics
- pyiron_base
- pyiron_potentialfit
- pyiron_snippets
- pyiron_workflow
- pylammpsmpi
- pymace
- pymov2gif
- pysqa
- python
- python-ace
- python-ternary
- pytorch
- pyxtal
- qe
- rdkit
- seaborn
- sim-atlas-toolkit
- sphinxdft
- semantikon
- sqsgenerator
- sysroot_linux-64
- tensorflow
- wget
- pip
- pip:
  - marimo-jupyter-extension==0.3.0
name: base
